version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - redis
    environment:
      - NODE_ENV=development
      - PORT=3001
      - MONGODB_URI=mongodb://root:example@mongodb:27017/agentic_sales?authSource=admin
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your_jwt_secret_here

  worker:
    build:
      context: .
      dockerfile: ./apps/worker/Dockerfile
    restart: always
    depends_on:
      - mongodb
      - redis
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://root:example@mongodb:27017/agentic_sales?authSource=admin
      - REDIS_URL=redis://redis:6379

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://api:3001

volumes:
  mongo_data:
  redis_data:
